import {
  SEO_AUTH_PATHS,
  SEO_PRIVATE_PATHS,
  SEO_PUBLIC_CHILDREN,
  SEO_THIN_PATHS,
} from '@revy/shared/constants'

/**
 * Robots (SPEC 22, 42).
 *
 * A route rather than a file in `public/`, for two reasons a static file
 * cannot solve:
 *
 *  1. **`Sitemap:` must be an absolute URL.** The protocol says so, and a
 *     relative one is not "resolved leniently" -- it is ignored, which is the
 *     worst kind of broken because the file still looks right. A static file
 *     has no way to know its own origin.
 *  2. **The paths come from `@revy/shared/constants`,** the same module
 *     `useIndexPolicy` reads. The hand-maintained copy was a list to keep in
 *     step by remembering to, and the failure was silent.
 *
 * The meta tag is still the rule search engines act on when deciding what may
 * appear in results; this file exists so a crawler does not have to fetch a
 * private page to be told to ignore it.
 */
export default defineEventHandler((event) => {
  const config = useRuntimeConfig()
  const origin = (
    (config.public.appUrl as string) || getRequestURL(event, { xForwardedHost: true }).origin
  ).replace(/\/$/, '')

  const lines = [
    '# Generated by server/routes/robots.txt.get.ts -- edit the SEO_* constants',
    '# in @revy/shared/constants, which useIndexPolicy reads as well.',
    '',
    'User-agent: *',
    '',
    '# Credential flows. A password-reset URL carries a token.',
    ...SEO_AUTH_PATHS.map((path) => `Disallow: ${path}`),
    '',
    '# Signed-in screens. A crawler only ever sees the sign-in wall here.',
    ...SEO_PRIVATE_PATHS.map((path) => `Disallow: ${path}`),
    '',
    /*
     * The carve-out, and the reason it is spelled this way.
     *
     * `Disallow: /lists` matches `/lists/<id>` too, which would block the
     * public lists the sitemap advertises -- telling Google about a page and
     * forbidding it to look. `Allow` wins over `Disallow` when its path is
     * longer, so the trailing slash makes children crawlable while `/lists`
     * itself stays blocked. Google and Bing both implement that rule; a
     * crawler that does not will simply skip the children too, which is the
     * conservative direction to be wrong in.
     */
    '# ...except a shared list, which is public content worth indexing.',
    ...SEO_PUBLIC_CHILDREN.map((path) => `Allow: ${path}/`),
    '',
    '# Search results: infinite URLs, no unique content.',
    ...SEO_THIN_PATHS.map((path) => `Disallow: ${path}`),
    '',
    '# The API is not a document.',
    'Disallow: /api/',
    '',
    `Sitemap: ${origin}/sitemap.xml`,
    '',
  ]

  setResponseHeader(event, 'content-type', 'text/plain; charset=utf-8')
  setResponseHeader(event, 'cache-control', 'public, max-age=3600')
  return lines.join('\n')
})
